# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2019, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.8\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-09-12 11:28+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../../library/asyncio-exceptions.rst:8
msgid "Exceptions"
msgstr ""

#: ../../library/asyncio-exceptions.rst:13
msgid "The operation has exceeded the given deadline."
msgstr ""

#: ../../library/asyncio-exceptions.rst:16
msgid "This exception is different from the builtin :exc:`TimeoutError` exception."
msgstr ""

#: ../../library/asyncio-exceptions.rst:22
msgid "The operation has been cancelled."
msgstr ""

#: ../../library/asyncio-exceptions.rst:24
msgid "This exception can be caught to perform custom operations when asyncio Tasks are cancelled.  In almost all situations the exception must be re-raised."
msgstr ""

#: ../../library/asyncio-exceptions.rst:30
msgid ":exc:`CancelledError` is now a subclass of :class:`BaseException`."
msgstr ""

#: ../../library/asyncio-exceptions.rst:35
msgid "Invalid internal state of :class:`Task` or :class:`Future`."
msgstr ""

#: ../../library/asyncio-exceptions.rst:37
msgid "Can be raised in situations like setting a result value for a *Future* object that already has a result value set."
msgstr ""

#: ../../library/asyncio-exceptions.rst:43
msgid "The \"sendfile\" syscall is not available for the given socket or file type."
msgstr ""

#: ../../library/asyncio-exceptions.rst:46
msgid "A subclass of :exc:`RuntimeError`."
msgstr ""

#: ../../library/asyncio-exceptions.rst:51
msgid "The requested read operation did not complete fully."
msgstr ""

#: ../../library/asyncio-exceptions.rst:53
msgid "Raised by the :ref:`asyncio stream APIs<asyncio-streams>`."
msgstr ""

#: ../../library/asyncio-exceptions.rst:55
msgid "This exception is a subclass of :exc:`EOFError`."
msgstr ""

#: ../../library/asyncio-exceptions.rst:59
msgid "The total number (:class:`int`) of expected bytes."
msgstr ""

#: ../../library/asyncio-exceptions.rst:63
msgid "A string of :class:`bytes` read before the end of stream was reached."
msgstr ""

#: ../../library/asyncio-exceptions.rst:68
msgid "Reached the buffer size limit while looking for a separator."
msgstr ""

#: ../../library/asyncio-exceptions.rst:70
msgid "Raised by the :ref:`asyncio stream APIs <asyncio-streams>`."
msgstr ""

#: ../../library/asyncio-exceptions.rst:74
msgid "The total number of to be consumed bytes."
msgstr ""

