Fix gather to propagate cancellation of itself even with return_exceptions.
