Fix AttributeError when calling get_stack on a PyAsyncGenObject Task